application: mrsdoyletheteabot
version: 2
runtime: python
api_version: 1

handlers:
- url: /stats
  script: stats/displaystats.py
  
- url: /.*
  script: bot/mrsdoyle.py

inbound_services:
- xmpp_message
- xmpp_presence
- xmpp_subscribe

