application: mrsdoyletheteabot
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: mrsdoyle.py

inbound_services:
- xmpp_message
- xmpp_presence
- xmpp_subscribe

